// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  // Use process.env here so generate doesn't throw when DATABASE_URL is not set
  datasource: {
    // when DATABASE_URL is missing, pass empty string to avoid throwing during config load
    url: process.env.DATABASE_URL ?? "",
  },
});
